on: [push, pull_request]

jobs:
  yay:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: packages
        key: packages-${{ hashFiles('packages.config') }}
        
    - run: |
        echo "2" > packages.config
        mkdir packages
        cd packages
        touch 2.txt
        ls
        cd ..
        ls
        cat packages.config
